packages:
  - 'packages/app/client'
  - 'packages/app/server'
  - 'packages/ui/components'
  - 'packages/ui/icons'
  - 'packages/ui/styles'
  - 'packages/spotify-social/mock'
  - 'packages/spotify-social/sdk'
  - 'packages/spotify-social/types'
  - 'packages/spotify-social/clients/packages/*'